### PR TITLE
feat: user cover/ for coverage output files

### PR DESCRIPTION
**Pull request by arkadyan**
This is the default directory written to by LcovEx.

Apply whitespace changes from Prettier.

### CODE REVIEW

**Comment by arkadyan** [comment]
@paulswartz Two notes on this:

1. I included a whitespace change automatically applied by my editor (I think probably Prettier). Let me know if you don't like that and I can remove it.
2. I didn't seem to have permission to push a branch to this repo, so I cloned it and went through my own account's repo. Not sure if this is the intended workflow or not for this project, but just FYI.

**Comment by arkadyan** [comment]
@paulswartz It looks like I also don't have permission to assign it to you for review (at least not after forgetting to do so when I created the PR).

**Review by paulswartz — APPROVED** [review]
🍰 do you have permission to merge?

**Comment by arkadyan** [comment]
@paulswartz I do not. It says, "Only those with write access to this repository can merge pull requests."

**Comment by paulswartz** [comment]
@arkadyan better now?

**Comment by arkadyan** [comment]
@paulswartz Yep! Thanks.

**Pull request merged**
